#+Title: Ùzje Mahjong
#+Date: 2020-09-06

*Ùzje Mahjong* is a variant of the traditional Mahjong game
that is seen all throughout the planet Earth,
but mostly concentrated in the eastern Asia.
The game has evolved considerably
since its unknown origin in the late 19th century from even older games,
and has spawned many variants throughout the world, and Ùzje is no exception.

The variant played in Ùzje is significantly different
from those played in nearby regions
and has elements from faraway regions as well,
with Japan being a particular source of it in particular.
It is also the only variant to radically alter the composition of the tiles,
which we will see later.
Ùzje mahjong also stands alone amongst other variants
in being able to support six or even eight players,
though this is not frequently done as getting that many people to play
is not easy.

Note that as with all mahjong variants, this game is separate and unrelated
to the tile-matching game that was invented much later on.

#  LocalWords:  Ùzje
